# Generated by Django 5.0.7 on 2024-07-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0002_remove_game_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='name_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
