# Generated by Django 5.0.7 on 2024-07-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='amenity_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='amenity_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='city_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='city_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='country_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='country_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='county_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='county_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='house_number_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='house_number_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='man_made_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='man_made_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='neighbourhood_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='neighbourhood_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='postcode_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='postcode_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='residential_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='residential_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='road_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='road_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='shop_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='shop_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='state_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='state_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
