# Generated by Django 5.0.7 on 2024-08-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0002_address_amenity_ru_address_amenity_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
