# Generated by Django 5.0.7 on 2024-07-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecobranch',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
