# Generated by Django 5.0.7 on 2024-07-20 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco_app', '0002_ecobranch_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecobranch',
            name='employee',
        ),
    ]
