# Generated by Django 5.0.7 on 2024-07-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_app', '0003_remove_ecobranch_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecobranch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
