# Generated by Django 5.0.7 on 2024-07-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco_app', '0004_ecobranch_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecobranch',
            name='is_active',
        ),
    ]
