# Generated by Django 5.0.7 on 2024-08-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_app', '0007_ecobranch_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecobranch',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
