# Generated by Django 5.0.7 on 2024-08-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_app', '0008_ecobranch_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecobranch',
            name='chief_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
