# Generated by Django 5.0.7 on 2024-08-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_app', '0009_ecobranch_chief_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecobranch',
            name='activity_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
