# Generated by Django 5.0.7 on 2024-07-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_ecobranchemployee_language_participant_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('tg_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian')], default='uz', max_length=2)),
            ],
            options={
                'db_table': 'admins',
            },
        ),
    ]
