# Generated by Django 5.0.7 on 2024-07-21 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0002_remove_game_employee'),
        ('users', '0006_remove_ecobranchemployee_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredqrcode',
            name='qrcode',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_app.qrcode'),
        ),
    ]
