# Generated by Django 5.0.7 on 2024-07-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_registeredqrcode_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredqrcode',
            name='winner',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Winner',
        ),
    ]
