# Generated by Django 5.0.7 on 2024-08-05 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_participant_suggested'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlasticCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('uzcard', 'UzCard'), ('humo', 'Humo')], default='uzcard', max_length=15)),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('card_date', models.DateField(blank=True, null=True)),
                ('card_cvv', models.CharField(blank=True, max_length=3, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='card_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.participant')),
            ],
            options={
                'db_table': 'plastic_cards',
            },
        ),
    ]
